### ISSUE TITLE
MC 1.14.4: Needle pointing in all directions

### ISSUE THREAD

**Issue by Knito58** [Tfarcenim/EnderCompass#1]
When standing still the needle moves to all directions. There's no favourite and I cannot decide where to go. I moved away from home with my ender compass thinking that maybe if I was nearer to one of  the strongholds this one would take over.
But no. Atm the compass is quite useless for me. Perhaps the config file shows some options? Nope. I did not find no config file at all (looking for endercompass, stronghold and compass).

I respect that you took over the project and keep it up. But the old version worked for me. This one does not work. 

MC 1.14.4
Forge 28.0.83
Ender Compass 1.0

**Comment by Tfarcenim** [comment]
world seed?

**Comment by Knito58** [comment]
-183979950711958773
Sorry was away from home for 4 days.
Home at  -200, -16

**Comment by Knito58** [comment]
Thank you, version 1.1 is working nicely.
