### ISSUE TITLE
Compass just spins on 1.15.2

### ISSUE THREAD

**Issue by tobi-polar** [Tfarcenim/EnderCompass#2]
Used /locate stronghold to find a stronghold, flew around it a bit, compass wasnt pointing to it at all..

**Comment by SapleMyrup** [comment]
> Used /locate stronghold to find a stronghold, flew around it a bit, compass wasnt pointing to it at all..

same thing on 1.15.2.

**Comment by Tfarcenim** [comment]
dupe of #4
